# Generated by Django 6.0.3 on 2026-05-05 09:31

import django.db.models.deletion
import django_choices_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'File'), (20, 'IFrame')])),
                ('file', models.FileField(blank=True, null=True, upload_to='EmergencyAlert/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EmergencyAlert', to='geo.adminarea')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_EmergencyAlert', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Alert',
                'verbose_name_plural': 'Emergency Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlertIframeUrl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('emergencyAlert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iframe_urls', to='works.emergencyalert')),
            ],
            options={
                'verbose_name': 'EmergencyAlert Iframe URL',
                'verbose_name_plural': 'EmergencyAlert Iframe URLs',
            },
        ),
    ]
