# Generated by Django 6.0.3 on 2026-05-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyalertiframeurl',
            options={'ordering': ['order'], 'verbose_name': 'EmergencyAlert Iframe URL', 'verbose_name_plural': 'EmergencyAlert Iframe URLs'},
        ),
        migrations.AddField(
            model_name='emergencyalertiframeurl',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
