# Generated by Django 6.0.3 on 2026-04-07 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('go_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('disaster_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('affected_pop', models.IntegerField(blank=True, null=True)),
                ('go_url', models.URLField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, help_text='Matched by name/pcode during sync.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='geo.adminarea')),
            ],
            options={
                'verbose_name': 'Emergency',
                'verbose_name_plural': 'Emergencies',
                'ordering': ['-start_date'],
            },
        ),
    ]
