name: ercs-backend

services:
  web:
    command: ./deploy/run_prod.sh
    environment:
      DEBUG: ${DEBUG:-false}
    volumes: !override
      - ./data/backend/media:/code/media
      - ./data/backend/static:/code/staticfiles
      - ipython_data_local:/root/.ipython/profile_default

  caddy:
    image: caddy:2
    restart: always
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/backend:/app-assets/server-static:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CADDY_EMAIL: ${CADDY_EMAIL?err}
      CADDY_BACKEND_HOST: ${CADDY_BACKEND_HOST?err}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config:
