# Generated by Django 6.0.3 on 2026-05-05 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='iframe_url',
        ),
        migrations.CreateModel(
            name='ResourceIframeUrl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iframe_urls', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Resource Iframe URL',
                'verbose_name_plural': 'Resource Iframe URLs',
            },
        ),
    ]
