# Generated by Django 6.0.3 on 2026-04-07 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('geo', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newspost',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='geo.adminarea'),
        ),
        migrations.AddField(
            model_name='newspostreport',
            name='newspost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspost_reports', to='content.newspost'),
        ),
        migrations.AddField(
            model_name='newspostreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspost_reports', to='reports.report'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='news_posts', through='content.NewsPostReport', to='reports.report'),
        ),
        migrations.AddConstraint(
            model_name='newspostreport',
            constraint=models.UniqueConstraint(fields=('newspost', 'report'), name='unique_newspost_report'),
        ),
    ]
