---
# Source: ercs-backend-helm/charts/app/templates/config/secret.yaml
kind: Secret
apiVersion: v1
metadata:
  name: release-name-ercs-secret
  labels:
    app: release-name-ercs
    environment: ALPHA
    release: release-name
type: Opaque
stringData:
  # secrets
  DJANGO_SECRET_KEY: "dummy-secret-key"
  POSTGRES_DB: "dummy"
  POSTGRES_HOST: "dummy"
  POSTGRES_PASSWORD: "dummy"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "dummy"

---
# Source: ercs-backend-helm/charts/app/templates/config/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: release-name-ercs-env-name
  labels:
    app: release-name-ercs
    environment: ALPHA
    release: release-name
data:
  # Configs
  APP_DOMAIN: "https://ercs.example.com"
  APP_ENVIRONMENT: "ALPHA"
  APP_RELEASE: "develop.xxxxxxxx"
  AWS_S3_ENABLED: "false"
  CSRF_COOKIE_DOMAIN: ".example.com"
  DEBUG: "false"
  FRONTEND_DOMAIN: "https://ercs-frontend.example.com"
  SENTRY_ENABLED: "false"
  SENTRY_PROFILE_SAMPLE_RATE: "0.8"
  SENTRY_TRACES_SAMPLE_RATE: "0.8"
  SESSION_COOKIE_DOMAIN: ".example.com"
  TIME_ZONE: "UTC"

---
# Source: ercs-backend-helm/charts/app/templates/api/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-ercs-api
  labels:
    app: release-name-ercs
    component: api
    environment: ALPHA
    release: release-name
spec:
  type: ClusterIP
  selector:
    app: release-name-ercs
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# Source: ercs-backend-helm/charts/app/templates/api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-ercs-api
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    reloader.stakater.com/auto: "true"
  labels:
    app: release-name-ercs
    component: api
    environment: ALPHA
    release: release-name
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: release-name-ercs
      component: api
  template:
    metadata:
      annotations:
        checksum/secret: 88fb2eb54fc8fca9dee7d1b4311e3ef332fa815e9c0237507067ab43e438b5ee
        checksum/configmap: 9b6e228187ac8ab2234203ac6f01a0e2ac96312620ff9e89d07efd47d849a0eb
      labels:
        app: release-name-ercs
        component: api
    spec:
      terminationGracePeriodSeconds: 38
      containers:
        - name: api
          image: "local.example.com/toggle-corp/ercs-backend:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command:
            - misc/prod/run_web.sh
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz/live/
              port: http
            periodSeconds: 20
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz/ready/
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready/
              port: http
            periodSeconds: 5
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: "0.3"
              memory: 0.4Gi
          envFrom:
            - secretRef:
                name: release-name-ercs-secret
            - configMapRef:
                name: release-name-ercs-env-name
          env:
            - name: APP_TYPE
              value: "web"
            - name: CACHE_REDIS_URL
              value: redis://ercs-dragonfly:6379/1
            - name: CELERY_REDIS_URL
              value: redis://ercs-dragonfly:6379/0
            
          lifecycle:
            preStop:
              sleep:
                seconds: 8

---
# Source: ercs-backend-helm/charts/app/templates/worker-addons/deployment.yaml
# Addon: beat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-ercs-worker-beat
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    reloader.stakater.com/auto: "true"
  labels:
    app: release-name-ercs
    component: worker-addon
    addon: beat
    environment: ALPHA
    release: release-name
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: release-name-ercs
      component: worker-addon
      addon: beat
  template:
    metadata:
      annotations:
        checksum/secret: 88fb2eb54fc8fca9dee7d1b4311e3ef332fa815e9c0237507067ab43e438b5ee
        checksum/configmap: 9b6e228187ac8ab2234203ac6f01a0e2ac96312620ff9e89d07efd47d849a0eb
      labels:
        app: release-name-ercs
        component: worker-addon
        addon: beat
    spec:
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 1Mi
          name: celery-heartbeat
      containers:
        - name: beat
          image: "local.example.com/toggle-corp/ercs-backend:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - main
            - beat
            - -l
            - INFO
            - --scheduler
            - banjo_utils.celery_health.persistent.HeartbeatPersistentScheduler
          livenessProbe:
            exec:
              command:
              - banjo-celery-probe
              - --max-age
              - "360"
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 5
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: "0.1"
              memory: 256Mi
          envFrom:
            - secretRef:
                name: release-name-ercs-secret
            - configMapRef:
                name: release-name-ercs-env-name
          env:
            - name: APP_TYPE
              value: "worker"
            - name: CACHE_REDIS_URL
              value: redis://ercs-dragonfly:6379/1
            - name: CELERY_REDIS_URL
              value: redis://ercs-dragonfly:6379/0
            
            - name: BANJO_CELERY_HEARTBEAT_FILE
              value: "/var/run/celery/beat_heartbeat"
          volumeMounts:
            - mountPath: /var/run/celery
              name: celery-heartbeat

---
# Source: ercs-backend-helm/charts/app/templates/worker/deployment.yaml
# Queue: default
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-ercs-worker-default
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    reloader.stakater.com/auto: "true"
  labels:
    app: release-name-ercs
    component: worker
    queue: default
    environment: ALPHA
    release: release-name
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: release-name-ercs
      component: worker
      queue: default
  template:
    metadata:
      annotations:
        checksum/secret: 88fb2eb54fc8fca9dee7d1b4311e3ef332fa815e9c0237507067ab43e438b5ee
        checksum/configmap: 9b6e228187ac8ab2234203ac6f01a0e2ac96312620ff9e89d07efd47d849a0eb
      labels:
        app: release-name-ercs
        component: worker
        queue: default
    spec:
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 1Mi
          name: celery-heartbeat
      containers:
        - name: worker
          command:
            - celery
            - -A
            - main
            - worker
            - -l
            - INFO
            - -Q
            - default
            - --concurrency
            - "1"
            - --max-tasks-per-child
            - "10"
          image: "local.example.com/toggle-corp/ercs-backend:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - banjo-celery-probe
            failureThreshold: 6
            periodSeconds: 20
            timeoutSeconds: 5
          startupProbe:
            exec:
              command:
              - banjo-celery-probe
            failureThreshold: 30
            periodSeconds: 5
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: "0.1"
              memory: 0.5Gi
          envFrom:
            - secretRef:
                name: release-name-ercs-secret
            - configMapRef:
                name: release-name-ercs-env-name
          env:
            - name: APP_TYPE
              value: "worker"
            - name: CACHE_REDIS_URL
              value: redis://ercs-dragonfly:6379/1
            - name: CELERY_REDIS_URL
              value: redis://ercs-dragonfly:6379/0
            
            - name: BANJO_CELERY_HEARTBEAT_FILE
              value: "/var/run/celery/worker_heartbeat"
          volumeMounts:
            - mountPath: /var/run/celery
              name: celery-heartbeat

---
# Source: ercs-backend-helm/charts/app/templates/hooks/job.yaml
# Hook: collect-static
apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-ercs-collect-static
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: release-name-ercs
    component: hook
    hookName: collect-static
    environment: ALPHA
    release: release-name
spec:
  template:
    metadata:
      annotations:
        checksum/secret: 88fb2eb54fc8fca9dee7d1b4311e3ef332fa815e9c0237507067ab43e438b5ee
        checksum/configmap: 9b6e228187ac8ab2234203ac6f01a0e2ac96312620ff9e89d07efd47d849a0eb
      labels:
        app: release-name-ercs
        component: hook
        hookName: collect-static
    spec:
      restartPolicy: "Never"
      containers:
        - name: collect-static
          image: "local.example.com/toggle-corp/ercs-backend:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command: 
            - ./manage.py
            - collectstatic
            - --noinput
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: "0.1"
              memory: 1Gi
          envFrom:
            - secretRef:
                name: release-name-ercs-secret
            - configMapRef:
                name: release-name-ercs-env-name
          env:
            - name: APP_TYPE
              value: "hook"
            - name: CACHE_REDIS_URL
              value: redis://ercs-dragonfly:6379/1
            - name: CELERY_REDIS_URL
              value: redis://ercs-dragonfly:6379/0
---
# Source: ercs-backend-helm/charts/app/templates/hooks/job.yaml
# Hook: db-migrate
apiVersion: batch/v1
kind: Job
metadata:
  generateName: release-name-ercs-db-migrate-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: release-name-ercs
    component: hook
    hookName: db-migrate
    environment: ALPHA
    release: release-name
spec:
  activeDeadlineSeconds: 3600
  ttlSecondsAfterFinished: 604800
  template:
    metadata:
      annotations:
        checksum/secret: 88fb2eb54fc8fca9dee7d1b4311e3ef332fa815e9c0237507067ab43e438b5ee
        checksum/configmap: 9b6e228187ac8ab2234203ac6f01a0e2ac96312620ff9e89d07efd47d849a0eb
      labels:
        app: release-name-ercs
        component: hook
        hookName: db-migrate
    spec:
      restartPolicy: "Never"
      containers:
        - name: db-migrate
          image: "local.example.com/toggle-corp/ercs-backend:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command: 
            - ./manage.py
            - migrate
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: "0.1"
              memory: 1Gi
          envFrom:
            - secretRef:
                name: release-name-ercs-secret
            - configMapRef:
                name: release-name-ercs-env-name
          env:
            - name: APP_TYPE
              value: "hook"
            - name: CACHE_REDIS_URL
              value: redis://ercs-dragonfly:6379/1
            - name: CELERY_REDIS_URL
              value: redis://ercs-dragonfly:6379/0
---
# Source: ercs-backend-helm/charts/app/templates/hooks/job.yaml
# Hook: wait-for-resources
apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-ercs-wait-for-resources
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: release-name-ercs
    component: hook
    hookName: wait-for-resources
    environment: ALPHA
    release: release-name
spec:
  template:
    metadata:
      annotations:
        checksum/secret: 88fb2eb54fc8fca9dee7d1b4311e3ef332fa815e9c0237507067ab43e438b5ee
        checksum/configmap: 9b6e228187ac8ab2234203ac6f01a0e2ac96312620ff9e89d07efd47d849a0eb
      labels:
        app: release-name-ercs
        component: hook
        hookName: wait-for-resources
    spec:
      restartPolicy: "Never"
      containers:
        - name: wait-for-resources
          image: "local.example.com/toggle-corp/ercs-backend:develop.xxxxxxxx"
          imagePullPolicy: IfNotPresent
          command: 
            - ./manage.py
            - wait_for_resources
            - --db
            - --cache
            - --celery-broker
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: "0.1"
              memory: 1Gi
          envFrom:
            - secretRef:
                name: release-name-ercs-secret
            - configMapRef:
                name: release-name-ercs-env-name
          env:
            - name: APP_TYPE
              value: "hook"
            - name: CACHE_REDIS_URL
              value: redis://ercs-dragonfly:6379/1
            - name: CELERY_REDIS_URL
              value: redis://ercs-dragonfly:6379/0
            

---
# Source: ercs-backend-helm/charts/app/templates/api/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-ercs-api
  labels:
    app: release-name-ercs
    component: api
    environment: ALPHA
    release: release-name
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    traefik.ingress.kubernetes.io/router.middlewares: default-ercs-body-size@kubernetescrd
spec:
  ingressClassName: "traefik"
  rules:
    - host: "ercs.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: release-name-ercs-api
                port:
                  number: 80

---
# Source: ercs-backend-helm/charts/app/templates/extraManifests.yaml
# Manifest: dragonflydb-cluster
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
  name: ercs-dragonfly
spec:
  args:
  - --dbfilename=mainSnapshot
  replicas: 1
  resources:
    limits:
      cpu: "1"
      memory: 750Mi
    requests:
      cpu: "0.1"
      memory: 500Mi
  snapshot:
    cron: '*/5 * * * *'
    persistentVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
# Source: ercs-backend-helm/charts/app/templates/extraManifests.yaml
# Manifest: ercs-body-size
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ercs-body-size
spec:
  buffering:
    maxRequestBodyBytes: 20971520
