# Generated by Django 6.0.3 on 2026-04-07 06:40

import django_choices_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('page', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Home'), (20, 'Operations'), (30, 'Project Mapping'), (40, 'Capacity & Resources'), (50, 'Alerts'), (60, 'Disaster Response')])),
                ('show_on_home', models.BooleanField(default=False, help_text='Surface this dashboard as a quick link on the homepage.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'External Dashboard',
                'verbose_name_plural': 'External Dashboards',
                'ordering': ['page', 'order'],
            },
        ),
    ]
