# Generated by Django 6.0.3 on 2026-05-07 06:11

import django.db.models.deletion
import django_choices_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityAndResource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_capacity_and_resource', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_and_resource', to='geo.adminarea')),
            ],
            options={
                'verbose_name': 'Capacity And Resource',
                'verbose_name_plural': 'Capacity And Resources',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExternalDashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('page', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Home'), (20, 'Operations'), (30, 'Project Mapping'), (40, 'Capacity & Resources'), (50, 'Emergency Alerts'), (60, 'Disaster Response'), (70, 'Emergency Responses')])),
                ('show_on_home', models.BooleanField(default=False, help_text='Surface this dashboard as a quick link on the homepage.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to='geo.adminarea')),
            ],
            options={
                'verbose_name': 'External Dashboard',
                'verbose_name_plural': 'External Dashboards',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CapacityAndResourceIframeUrl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('capacity_and_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iframe_urls', to='dashboards.capacityandresource')),
                ('dashboard', models.ForeignKey(limit_choices_to={'page': 40}, on_delete=django.db.models.deletion.PROTECT, related_name='capacity_and_resource_iframe_urls', to='dashboards.externaldashboard')),
            ],
            options={
                'verbose_name': 'Capacity And Resource Iframe URL',
                'verbose_name_plural': 'Capacity And Resource Iframe URLs',
                'ordering': ['order'],
                'unique_together': {('capacity_and_resource', 'dashboard')},
            },
        ),
    ]
