# Generated by Django 6.0.3 on 2026-05-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacityandresource',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='capacityandresourceiframeurl',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
