# Generated by Django 6.0.3 on 2026-06-22 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacityandresource',
            name='dashboards',
        ),
        migrations.AddField(
            model_name='externaldashboard',
            name='capacity_and_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to='dashboards.capacityandresource'),
        ),
    ]
