# Generated by Django 6.0.3 on 2026-05-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_alter_capacityandresource_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capacityandresourceiframeurl',
            unique_together={('capacity_and_resource', 'dashboard')},
        ),
        migrations.AlterField(
            model_name='capacityandresourceiframeurl',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='capacityandresourceiframeurl',
            unique_together={('capacity_and_resource', 'dashboard'), ('capacity_and_resource', 'order')},
        ),
    ]
