# Generated by Django 6.0.8 on 2026-09-01 10:25

import django.db.models.deletion
import django_choices_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_add_ifrc_id_to_adminarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboSyncState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Emergency Alert'), (20, 'Rapid Needs Assessment'), (30, 'Emergency Field')], unique=True)),
                ('asset_uid', models.CharField(max_length=32)),
                ('last_fetched_at', models.DateTimeField(blank=True, help_text='Timestamp of the last *successful* fetch+reconcile.', null=True)),
                ('last_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], default='', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('record_count', models.IntegerField(default=0, help_text='Rows stored for this form after the last success.')),
            ],
            options={
                'verbose_name': 'Kobo Sync State',
                'verbose_name_plural': 'Kobo Sync States',
            },
        ),
        migrations.CreateModel(
            name='KoboSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Emergency Alert'), (20, 'Rapid Needs Assessment'), (30, 'Emergency Field')])),
                ('asset_uid', models.CharField(max_length=32)),
                ('kobo_id', models.IntegerField(help_text='Kobo `_id` — stable submission id, used as the upsert key.')),
                ('submission_time', models.DateTimeField(blank=True, help_text='Kobo `_submission_time`. Nullable: a record with a missing/unparseable value is still mirrored.', null=True)),
                ('validation_status', models.CharField(blank=True, default='', help_text="Kobo `_validation_status.uid`, e.g. 'validation_status_approved'. Empty if unset.", max_length=64)),
                ('emergency_code', models.CharField(blank=True, help_text='Links Alert/RNA/Field submissions for the same emergency. Derived on sync.', max_length=128, null=True)),
                ('raw', models.JSONField(help_text='The full Kobo record, verbatim.')),
                ('region', models.ForeignKey(blank=True, help_text='Best-effort match of the reporting region name during sync.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kobo_submissions', to='geo.adminarea')),
            ],
            options={
                'verbose_name': 'Kobo Submission',
                'verbose_name_plural': 'Kobo Submissions',
                'ordering': ['-submission_time', '-kobo_id'],
                'indexes': [models.Index(fields=['form', 'validation_status'], name='kobo_kobosu_form_670f9e_idx'), models.Index(fields=['emergency_code'], name='kobo_kobosu_emergen_37f5ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset_uid', 'kobo_id'), name='uniq_kobo_submission')],
            },
        ),
    ]
