# Generated by Django 6.0.8 on 2026-09-15 10:06

import django_choices_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboFormSchema',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Emergency Alert'), (20, 'Rapid Needs Assessment'), (30, 'Emergency Field')], unique=True)),
                ('asset_uid', models.CharField(max_length=32)),
                ('labels', models.JSONField(default=dict, help_text='Precomputed maps: {"choices": {list: {code: label}}, "fields": {leaf: {"list", "multiple"}}}.')),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kobo Form Schema',
                'verbose_name_plural': 'Kobo Form Schemas',
            },
        ),
    ]
