# Generated by Django 6.0.8 on 2026-09-08 06:12

import django.db.models.deletion
import django_choices_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_add_ifrc_id_to_adminarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PmerReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='pmer/')),
                ('category', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'DPR (Disaster Preparedness Report)'), (20, 'DRR (Disaster Risk Reduction)'), (30, 'Health & WASH'), (40, 'Volunteer Service / Membership')])),
                ('report_type', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Strategic Plan'), (20, 'Annual Plan'), (30, 'Annual Report'), (40, 'Mid-term Review Report')])),
                ('department', models.CharField(blank=True, max_length=250, null=True)),
                ('project', models.CharField(blank=True, max_length=250, null=True)),
                ('visibility', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Public'), (20, 'Private')], default=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pmer_reports', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmer_region', to='geo.adminarea')),
            ],
            options={
                'verbose_name': 'PMER Report',
                'verbose_name_plural': 'PMER Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
