# Generated by Django 6.0.3 on 2026-04-28 04:41

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='region',
            field=models.ForeignKey(blank=True, help_text='AdminArea at region level (level=20).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='geo.adminarea'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='sex',
            field=django_choices_field.fields.IntegerChoicesField(blank=True, choices=[(10, 'Male'), (20, 'Female'), (30, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='training',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='woreda',
            field=models.ForeignKey(blank=True, help_text='AdminArea at woreda level (level=40).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members_by_woreda', to='geo.adminarea'),
        ),
    ]
