# Generated by Django 6.0.3 on 2026-08-17 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_add_ifrc_id_to_adminarea'),
        ('teams', '0002_teammember_field_of_study_teammember_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='region',
            field=models.ForeignKey(default='', help_text='AdminArea at region level (level=20).', on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='geo.adminarea'),
            preserve_default=False,
        ),
    ]
