# Generated by Django 6.0.3 on 2026-04-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/covers/'),
        ),
    ]
