# Generated by Django 6.0.5 on 2026-05-27 06:39

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Report'), (20, 'Manual'), (30, 'Policy'), (40, 'Guideline'), (50, 'Online Interactive')], default=10),
        ),
    ]
