# Generated by Django 6.0.5 on 2026-05-27 06:44

import django_choices_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=2000)),
                ('link_type', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Internal'), (20, 'External')])),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['title'],
            },
        ),
    ]
