# Generated by Django 6.0.5 on 2026-06-04 06:33

import django.db.models.deletion
import django_choices_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extracted_contents', models.JSONField(blank=True, null=True)),
                ('search_text', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('status', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Pending'), (20, 'In Progress'), (30, 'Success'), (40, 'Failure')], default=10)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_extraction', to='reports.report')),
            ],
            options={
                'verbose_name': 'Document Extraction',
                'verbose_name_plural': 'Document Extractions',
            },
        ),
    ]
