# Generated by Django 6.0.3 on 2026-06-10 06:44

import django.db.models.deletion
import django_choices_field.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_create_vector_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentextraction',
            name='extracted_contents',
        ),
        migrations.RemoveField(
            model_name='documentextraction',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='documentextraction',
            name='summary',
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='chunk_type',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Extracted Content'), (2, 'Document Summary'), (3, 'Page Summary'), (4, 'Keywords'), (5, 'Table'), (6, 'Chart')], default=2),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='page_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='documentextraction',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_extractions', to='reports.report'),
        ),
    ]
