# Generated by Django 6.0.3 on 2026-06-30 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_create_hnsw_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='thematic_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.thematicarea'),
        ),
    ]
