# Generated by Django 6.0.3 on 2026-08-24

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_documentextraction_chunk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentextraction',
            name='chunk_type',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Extracted Content'), (2, 'Document Summary'), (3, 'Page Summary'), (4, 'Keywords'), (5, 'Table'), (6, 'Chart'), (7, 'Title'), (8, 'Description'), (9, 'Document Summary Short')], default=2),
        ),
    ]
