apiVersion: v2
name: ercs-backend-helm
description: "Helm Chart to deploy the ERCS EOC Backend"
type: application
version: 0.1.0-SET-BY-CICD
appVersion: "1.0.0"
sources:
  - https://github.com/toggle-corp/ercs-backend

dependencies:
  - name: banjo-helm
    alias: app
    version: 0.4.1
    repository: oci://ghcr.io/toggle-corp
