# Generated by Django 6.0.3 on 2026-04-07 06:40

import django.db.models.deletion
import django_choices_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_am', models.CharField(blank=True, max_length=255, null=True)),
                ('level', django_choices_field.fields.IntegerChoicesField(choices=[(10, 'Country'), (20, 'Region'), (30, 'Zone'), (40, 'Woreda')])),
                ('geo_shape', models.JSONField(blank=True, null=True)),
                ('pcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('centroid_lon', models.FloatField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='geo.adminarea')),
            ],
            options={
                'verbose_name': 'Admin Area',
                'verbose_name_plural': 'Admin Areas',
                'ordering': ['level', 'name'],
            },
        ),
    ]
