# Generated by Django 6.0.3 on 2026-06-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminarea',
            name='ifrc_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
